### ISSUE TITLE
Both Lumo and Material themes are bundled in production mode

### ISSUE THREAD

**Issue by brp-oskar** [devsoap/gradle-vaadin-flow#178] opened 2019-01-03 10:35 UTC
**Desktop:**
 - OS: Windows
 - JDK 8
 - Gradle version: 5.0
 - Vaadin Plugin version: 1.0.0.RC6

**Describe the bug**
Both Lumo and Material theme files are included when bundling web components to a single html file. It will result in unexpected behavior when duplicate css rules will be applied to each web component.

**To Reproduce**
1. Clone project [beverage-starter-flow-gradle](https://github.com/devsoap/examples/tree/master/beverage-starter-flow-gradle)
2. Add `vaadin.productionMode = true` in `build.gradle` 
3. Build the project
4. The generated `vaadin-flow-bundle-manifest.json` will contain files for both Lumo and Material.
```
"bower_components/vaadin-checkbox/vaadin-checkbox.html",
"bower_components/vaadin-checkbox/theme/lumo/vaadin-checkbox.html",
"bower_components/vaadin-checkbox/theme/lumo/vaadin-checkbox-styles.html",
"bower_components/vaadin-checkbox/src/vaadin-checkbox.html",
"bower_components/vaadin-checkbox/theme/material/vaadin-checkbox-group.html",
"bower_components/vaadin-checkbox/theme/material/vaadin-checkbox-group-styles.html",
```

**Expected behavior**
Vaadin's own plugin for Maven will search for annotation `@Theme` in the source code to detect the theme to use and then filters the files to bundle. I think this plugin should do the same as that plugin.

**Additional context**
Vaadin Flow Maven plugin has a class [ThemedURLTranslator](https://github.com/vaadin/flow/blob/4796bd7b6fac054ae7ac4282f84a590c7fdd6056/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/ThemedURLTranslator.java) that uses the theme from the `@Theme` annotation.

**Comment by brp-oskar** [comment] 2019-01-03 11:41
As I can see there is a difference between how this plugin and Vaadin Flow Maven plugin resolves frontend dependencies. This plugin finds `bower.json` ([TranspileDependenciesTask.groovy](https://github.com/devsoap/gradle-vaadin-flow/blob/master/src/main/groovy/com/devsoap/vaadinflow/tasks/TranspileDependenciesTask.groovy)) files and use the specified "main" files as "entry points". The maven plugin search the source code for `@HtmlImport` ([FrontendDataProvider.java](https://github.com/vaadin/flow/blob/94f1a8ebe5a6934439d199fc080d46d07c824b84/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendDataProvider.java)) and use them as "entry points". Is there a reason for that?

I think it would be better that both plugin works the same. Is there any design meetings between you and the Vaadin team?

**Comment by johndevs** [comment] 2019-01-12 17:36
> Both Lumo and Material theme files are included when bundling web components to a single html file. It will result in unexpected behavior when duplicate css rules will be applied to each web component.

The issue is not really in the plugin, but the Vaadin platform release that depends on both themes and pulls both of them in. The plugin will add all web components that you put in the classpath as imports.

To exclude a dependency from the default set, you need to replace ``vaadin.autoconfigure()`` with manual dependency handling as described in https://github.com/devsoap/gradle-vaadin-flow/wiki/Dependency-management .

If you still want to use the full platform, then it looks like this:
```
dependencies {
    compile vaadin.bom()
    compileOnly vaadin.servletApi()
    compile (vaadin.platform()) {
        // Application is using Material theme, Lumo not needed
        exclude group: 'com.vaadin', module: 'vaadin-lumo-theme'
    }
}
```
If you want  a narrower set of components you could just include the core ones
```
dependencies {
   compile vaadin.bom()
   compile vaadin.core()
   compile vaadin.dependency('material-theme')
}
```
While ``vaadin.autoconfigure()`` is there to get you the defaults and get started on any theme, I recommend once you have nailed down the requirements to replace the autoconfigure with a more fine grained dependency definition and only define the dependencies you really need to be on the classpath.

> As I can see there is a difference between how this plugin and Vaadin Flow Maven plugin resolves frontend dependencies. This plugin finds bower.json (TranspileDependenciesTask.groovy) files and use the specified "main" files as "entry points". The maven plugin search the source code for @HtmlImport (FrontendDataProvider.java) and use them as "entry points". Is there a reason for that?

It is unfortunate the the creators of the Maven plugin has taken the route of reading source files to determine behavior. Scanning source code is always error prone, especially since this Gradle plugin needs to support not only Java but also Groovy and Kotlin. Pattern matching source files becomes a nightmare in the end. This is why the Gradle plugin uses the actual dependencies defined on the classpath and scans their data to resolve the imports (JSON is structured format, while source files are not). I cannot tell why their decision has been to do it in that way.

> I think it would be better that both plugin works the same. Is there any design meetings between you and the Vaadin team?

While I do agree in some ways that it would be beneficial if the plugins would work alike, in practice it is not really possible as that would make it hard to implement Gradle specific features. One of the major differences between the plugins right now is that the Maven plugin relies heavily on Grunt (https://gruntjs.com) to do the building while the Gradle plugin is a fully native Java/Groovy implementation which means that Gradle has full control in the caching and execution of the tasks. Having full control allows us to reap the full benefits of the Gradle platform features and performance enhancements like the Gradle Cache.

**Comment by johndevs** [comment] 2019-01-25 06:07
I've added support for filtering out imports so you can more easily control what goes into the bundle.

The filter can be used like this:
```
vaadinTranspileDependencies {
  importExcludes = [
     '.*/theme/material/.*',
     '.*/vaadin-material-styles/.*'
  ]
}
```
With that you should be able to remove the extra theme from the bundle. It will be available in the next RC release.

I'll see if I can get a more elegant solution for this in 1.1 which does not require loading the whole application classpath into memory and doing reflection operations to find the theme (like the maven plugin does it).

**Comment by johndevs** [comment] 2019-01-27 18:56
RC7 is now released. 

I updated the beverage starter project with the correct Gradle configuration to exclude the Material theme https://github.com/devsoap/examples/blob/master/beverage-starter-flow-gradle/build.gradle#L48

**Comment by johndevs** [comment] 2019-01-28 15:55
In RC8 these will improve as follows:

By default no theme will be included when using ``vaadin.core()`` or ``vaadin.platform()`` dependencies manually. It is required to include the theme you want manually by defining a dependency to it. E.g.
```
dependencies {
     compile vaadin.bom()
     compile vaadin.core()
     compile vaadin.lumoTheme()
     //compile vaadin.materialTheme()   // Alternatively
}
```
``vaadin.autoconfigure()`` will by default include the *Lumo* theme ONLY.

In production mode the theme imports are filtered automatically according to which theme is selected.

**Closed** 2019-01-29 06:12 UTC
Labels: enhancement

**Comment by alabotski** [comment] 2019-01-29 10:06
I try build project with lumo styles

```// In production mode we want to exclude the Material styles imported from all vaadin components
vaadinTranspileDependencies {
    importExcludes = [
            '.*/theme/lumo/.*',
            '.*/vaadin-lumo-styles/.*'
    ]
}

// We don't want the Material style Maven dependencies in our project either
configurations.all {
    exclude group: 'com.vaadin', module: 'vaadin-lumo-theme'
    exclude group: 'org.webjars.bowergithub.vaadin', module: 'vaadin-lumo-styles'
}```

All work well, but when I try build it with Material styles I have error
```// In production mode we want to exclude the Material styles imported from all vaadin components
vaadinTranspileDependencies {
    importExcludes = [
            '.*/theme/lumo/.*',
            '.*/vaadin-lumo-styles/.*'
    ]
}

// We don't want the Material style Maven dependencies in our project either
configurations.all {
    exclude group: 'com.vaadin', module: 'vaadin-lumo-theme'
    exclude group: 'org.webjars.bowergithub.vaadin', module: 'vaadin-lumo-styles'
}```

Such error

```9 warnings

> Task :vaadinTranspileDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinTranspileDependencies'.
> Process 'command '/Users/lesharb/Workspace/test/test-flow/.gradle/yarn/yarn-v1.12.3/bin/yarn'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 2s
12 actionable tasks: 8 executed, 4 up-to-date
LeshaRB:test-flow lesharb$ 
```

**Comment by alabotski** [comment] 2019-01-29 10:17
```
13:12:12.831 [DEBUG] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] 
13:12:16.307 [LIFECYCLE] [org.gradle.process.internal.health.memory.MemoryManager] 
13:12:16.307 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17179869184, Free: 6180225024}
13:12:16.307 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17179869184, Free: 6180225024}
13:12:16.307 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 2863661056, Committed: 2299527168}
13:12:19.529 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
13:12:19.529 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
13:12:19.529 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
13:12:19.529 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
13:12:19.529 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
13:12:19.529 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
13:12:19.530 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
13:12:21.307 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17179869184, Free: 6067277824}
13:12:21.307 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17179869184, Free: 6067277824}
13:12:21.307 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 2863661056, Committed: 2299527168}
13:12:13.246 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
13:12:13.246 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :vaadinTranspileDependencies
13:12:22.487 [DEBUG] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] error:    Promise rejection: Error: ENOENT: no such file or directory, open '/Users/lesharb/Workspace/test/test-flow/build/frontend/bower_components/vaadin-lumo-styles/color.html'

13:12:22.487 [DEBUG] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] 
13:12:22.487 [DEBUG] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] error:    Error: ENOENT: no such file or directory, open '/Users/lesharb/Workspace/test/test-flow/build/frontend/bower_components/vaadin-lumo-styles/color.html'

13:12:22.487 [DEBUG] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] 
13:12:22.534 [INFO] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] error Command failed with exit code 1.

13:12:22.534 [INFO] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] 
13:12:22.534 [DEBUG] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

13:12:22.534 [DEBUG] [com.devsoap.vaadinflow.util.LogUtils$LogOutputStream] 
13:12:22.542 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
13:12:22.543 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/Users/lesharb/Workspace/test/test-flow/.gradle/yarn/yarn-v1.12.3/bin/yarn'' finished with exit value 1 (state: FAILED)
13:12:22.543 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute run for :vaadinTranspileDependencies'
13:12:22.543 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute run for :vaadinTranspileDependencies' completed
13:12:22.543 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property es5dir (Output) for task ':vaadinTranspileDependencies'
13:12:22.543 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property es6dir (Output) for task ':vaadinTranspileDependencies'
13:12:22.543 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property html (Output) for task ':vaadinTranspileDependencies'
13:12:26.309 [LIFECYCLE] [org.gradle.process.internal.health.memory.MemoryManager] 
13:12:26.309 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17179869184, Free: 6267035648}
13:12:26.309 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17179869184, Free: 6267035648}
13:12:26.309 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 2863661056, Committed: 2299527168}
13:12:22.546 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
13:12:22.546 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :vaadinTranspileDependencies FAILED
13:12:29.455 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property manifestJson (Output) for task ':vaadinTranspileDependencies'
13:12:29.455 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property polymerJson (Output) for task ':vaadinTranspileDependencies'
13:12:29.455 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.comboBoxConnector.js for task ':vaadinTranspileDependencies'
13:12:29.455 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.contextMenuConnector.js for task ':vaadinTranspileDependencies'
13:12:29.455 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.datepickerConnector.js for task ':vaadinTranspileDependencies'
13:12:29.456 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.flow-component-renderer.html for task ':vaadinTranspileDependencies'
13:12:29.456 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.gridConnector.js for task ':vaadinTranspileDependencies'
13:12:29.456 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.ironListConnector.js for task ':vaadinTranspileDependencies'
13:12:29.456 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.ironListStyles.css for task ':vaadinTranspileDependencies'
13:12:29.456 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.timepickerConnector.js for task ':vaadinTranspileDependencies'
13:12:29.457 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property staticResources.vaadin-grid-flow-selection-column.html for task ':vaadinTranspileDependencies'
13:12:29.457 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property stylesDir (Output) for task ':vaadinTranspileDependencies'
13:12:29.457 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property templatesDir (Output) for task ':vaadinTranspileDependencies'
13:12:29.457 [DEBUG] [org.gradle.internal.execution.impl.steps.CacheStep] Not storing result of task ':vaadinTranspileDependencies' in cache because the execution failed
13:12:29.457 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
13:12:29.458 [DEBUG] [org.gradle.api.Project] Executing post task hook for NodePluginAction_Decorated for task vaadinTranspileDependencies
13:12:29.458 [DEBUG] [org.gradle.api.Project] Executing post task hook for GrettyPluginAction_Decorated for task vaadinTranspileDependencies
13:12:29.458 [DEBUG] [org.gradle.api.Project] Executing post task hook for VaadinFlowPluginAction_Decorated for task vaadinTranspileDependencies
13:12:29.458 [DEBUG] [org.gradle.api.Project] Executing post task hook for WarPluginAction_Decorated for task vaadinTranspileDependencies
13:12:29.458 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :vaadinTranspileDependencies'
13:12:29.458 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :vaadinTranspileDependencies' completed
13:12:29.458 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :vaadinTranspileDependencies (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 53.582 secs.
13:12:29.458 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':' Thread 2: released lock on :
13:12:29.458 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.34 completed (1 worker(s) in use)
13:12:29.458 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':' Thread 2: released lock on root.1.34
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 2,5,main]] finished, busy: 3 mins 4.141 secs, idle: 1 mins 1.918 secs
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 7,5,main]] finished, busy: 0.0 secs, idle: 4 mins 6.059 secs
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 4 mins 6.059 secs
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 4,5,main]] finished, busy: 0.0 secs, idle: 4 mins 6.059 secs
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 5,5,main]] finished, busy: 0.0 secs, idle: 4 mins 6.059 secs
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 6,5,main]] finished, busy: 0.0 secs, idle: 4 mins 6.059 secs
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Daemon worker Thread 13,5,main]] finished, busy: 0.0 secs, idle: 4 mins 6.059 secs
13:12:29.459 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':',5,main]] finished, busy: 54.413 secs, idle: 3 mins 11.647 secs
13:12:29.459 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskExecutionGraph] Timing: Executing the DAG took 4 mins 6.061 secs
13:12:29.460 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
13:12:29.460 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
13:12:29.461 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
13:12:29.461 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 13: released lock on root.1
13:12:29.461 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':vaadinTranspileDependencies'.
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command '/Users/lesharb/Workspace/test/test-flow/.gradle/yarn/yarn-v1.12.3/bin/yarn'' finished with non-zero exit value 1
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
13:12:29.462 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
13:12:29.463 [WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
13:12:29.463 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
13:12:29.463 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 4m 7s
13:12:29.463 [LIFECYCLE] [org.gradle.internal.buildevents.TaskExecutionStatisticsReporter] 12 actionable tasks: 8 executed, 4 up-to-date
13:12:29.463 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
13:12:29.463 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
13:12:29.466 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file content cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/fileContent)
13:12:29.466 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file content cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/fileContent).
13:12:29.467 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Build Output Cleanup Cache (/Users/lesharb/Workspace/test/test-flow/.gradle/buildOutputCleanup)
13:12:29.467 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache outputFiles.bin (/Users/lesharb/Workspace/test/test-flow/.gradle/buildOutputCleanup/outputFiles.bin)
13:12:29.467 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Build Output Cleanup Cache (/Users/lesharb/Workspace/test/test-flow/.gradle/buildOutputCleanup).
13:12:29.468 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for execution history cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/executionHistory)
13:12:29.468 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache executionHistory.bin (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/executionHistory/executionHistory.bin)
13:12:29.468 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on execution history cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/executionHistory).
13:12:29.469 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Java compile cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/javaCompile)
13:12:29.469 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache taskHistory.bin (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/javaCompile/taskHistory.bin)
13:12:29.469 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Java compile cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/javaCompile).
13:12:29.470 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-supplier (/Users/lesharb/.gradle/caches/5.1.1/md-supplier)
13:12:29.470 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-supplier (/Users/lesharb/.gradle/caches/5.1.1/md-supplier).
13:12:29.471 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-rule (/Users/lesharb/.gradle/caches/5.1.1/md-rule)
13:12:29.471 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-rule (/Users/lesharb/.gradle/caches/5.1.1/md-rule).
13:12:29.472 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 148, disk reads: 2 (avg: 0.001 secs, total: 0.003 secs)
13:12:29.472 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
13:12:29.475 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 6 resolution results binary files in 0.002 secs
13:12:29.478 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
13:12:29.478 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
13:12:29.479 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/fileHashes)
13:12:29.479 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileHashes.bin (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/fileHashes/fileHashes.bin)
13:12:29.479 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/fileHashes).
13:12:29.480 [DEBUG] [org.gradle.cache.internal.DefaultPersistentDirectoryStore] VCS Checkout Cache (/Users/lesharb/Workspace/test/test-flow/.gradle/vcs-1) has last been fully cleaned up 1 hours ago
13:12:29.480 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS Checkout Cache (/Users/lesharb/Workspace/test/test-flow/.gradle/vcs-1) was closed 0 times.
13:12:29.480 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS metadata (/Users/lesharb/Workspace/test/test-flow/.gradle/5.1.1/vcsMetadata-1) was closed 0 times.
13:12:29.486 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
13:12:29.540 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@14ad196b
13:12:29.540 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 14: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
13:12:29.541 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Success[value=org.gradle.launcher.exec.BuildActionResult@7c6908d7] from daemon DaemonInfo{pid=1419, address=[dc0a601e-f55a-418e-9e8b-0f8b43d8db0a port:50628, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1548756057067, context=DefaultDaemonContext[uid=3b710aa2-a717-486d-a79c-e5c284b0d24e,javaHome=/Users/lesharb/.sdkman/candidates/java/8.0.191-oracle,daemonRegistryDir=/Users/lesharb/.gradle/daemon,pid=1419,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxPermSize=2048m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx3g,-Dfile.encoding=UTF-8,-Duser.country=BY,-Duser.language=en,-Duser.variant]} (build should be done).
13:12:29.541 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
13:12:29.541 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
LeshaRB:test-flow lesharb$ 
```
