### ISSUE TITLE
Plugin doesn't work with Kotlin 1.3

### ISSUE THREAD

**Issue by mosi0815** [devsoap/gradle-vaadin-flow#132] opened 2018-10-06 00:04 UTC
Long story short. I try to port my demo app to JDK11. To make kapt work I need Kotlin 1.3. So I started experimenting with the latest EAP version. 1.3.0-rc-57
This leads to the following error if the vaadin-flow plugin is enabled:
```
A problem occurred configuring root project 'gradletest'.
> Cannot change strategy of configuration ':kotlinScriptDef' after it has been resolved.
```

I tried it with a Kotlin build script and a Groovy one. Same result.

**Comment by mosi0815** [comment] 2018-10-18 13:13
I don't think this is an enhancement. Gradle 5 is going to use Kotlin 1.3 as default for kts buildscripts which means that it's highly recommended to use it for projects aswell to avoid incompatibilities with the standard library.

**Comment by johndevs** [comment] 2018-11-26 18:09
Hi, 

Now that Gradle 5.0.0 was released I tested this on https://github.com/devsoap/examples/tree/master/karibu10-helloworld-application. It is a Kotlin project using Kotlin 1.3.10 as well as the Karibu DSL library.

It seemed to work fine and I couldn't reproduce this. Could you try updating your project and check against the example project to see if there is any difference?

**Comment by mosi0815** [comment] 2018-11-27 13:20
Now it works. Thank you!

**Comment by johndevs** [comment] 2018-11-27 18:22
Great to hear! I'll close this then.

**Closed by johndevs** 2018-11-27 18:22 UTC
