### ISSUE TITLE
Could not create plugin of type 'VaadinFlowPlugin'

### ISSUE THREAD

**Issue by dwalters128** [devsoap/gradle-vaadin-flow#111] opened 2018-09-11 08:52 UTC
(Gradle 4.4)

An exception occurred applying plugin request [id: 'com.devsoap.vaadin-flow', version: '1.0.0.M4.1']
> Failed to apply plugin [id 'com.devsoap.vaadin-flow']
   > Could not create plugin of type 'VaadinFlowPlugin'

[build.gradle.txt](https://github.com/devsoap/gradle-vaadin-flow/files/2370235/build.gradle.txt)

**Comment by johndevs** [comment] 2018-09-11 09:00
Duplicate of #108 , you need to upgrade your Gradle to at least **Gradle 4.6**.

**Closed by johndevs** 2018-09-11 09:00 UTC
